name: CI/CD

on:
  push:
    branches:
      - "master"

env:
  TWITTER_API_KEY: ${{secrets.TWITTER_API_KEY}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.19.0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: palanikannanm1437/devopscomm-rc4-image
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push to docker hub
        uses: docker/build-push-action@v4
        with:
          context: "./app"
          file: "Dockerfile.prod"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}